// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NekoSubscription.Core.Subscriptions;

#nullable disable

namespace NekoSubscription.Core.Subscriptions.Migrations
{
    [DbContext(typeof(SubscriptionDbContext))]
    partial class SubscriptionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("NekoSubscription.Entities.Subscriptions.CustomField", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("BooleanValue")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CustomSubscriptionId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DateValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("FieldType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NumberValue")
                        .HasPrecision(28, 8)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TextValue")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("UrlValue")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FieldType");

                    b.HasIndex("CustomSubscriptionId", "SortOrder");

                    b.ToTable("CustomFields", null, t =>
                        {
                            t.HasCheckConstraint("CK_CustomFields_TypedValue", "(FieldType = 0 AND TextValue IS NOT NULL AND NumberValue IS NULL AND BooleanValue IS NULL AND DateValue IS NULL AND UrlValue IS NULL) OR (FieldType = 1 AND TextValue IS NULL AND NumberValue IS NOT NULL AND BooleanValue IS NULL AND DateValue IS NULL AND UrlValue IS NULL) OR (FieldType = 2 AND TextValue IS NULL AND NumberValue IS NULL AND BooleanValue IS NOT NULL AND DateValue IS NULL AND UrlValue IS NULL) OR (FieldType = 3 AND TextValue IS NULL AND NumberValue IS NULL AND BooleanValue IS NULL AND DateValue IS NOT NULL AND UrlValue IS NULL) OR (FieldType = 4 AND TextValue IS NULL AND NumberValue IS NULL AND BooleanValue IS NULL AND DateValue IS NULL AND UrlValue IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("NekoSubscription.Entities.Subscriptions.PaymentProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountIdentifier")
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Channel")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Channel");

                    b.HasIndex("IsArchived");

                    b.ToTable("PaymentProfiles", null, t =>
                        {
                            t.HasCheckConstraint("CK_PaymentProfiles_ArchiveState", "(IsArchived = 0 AND ArchivedAtUtc IS NULL) OR (IsArchived = 1 AND ArchivedAtUtc IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("NekoSubscription.Entities.Subscriptions.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountName")
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConfirmationStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Importance")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("IncludedWithSubscriptionId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LifecycleStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ManagementUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PaymentProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConfirmationStatus");

                    b.HasIndex("IncludedWithSubscriptionId");

                    b.HasIndex("IsArchived");

                    b.HasIndex("PaymentProfileId");

                    b.ToTable("Subscriptions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Subscriptions_ArchiveState", "(IsArchived = 0 AND ArchivedAtUtc IS NULL) OR (IsArchived = 1 AND ArchivedAtUtc IS NOT NULL)");

                            t.HasCheckConstraint("CK_Subscriptions_DeleteState", "(IsDeleted = 0 AND DeletedAtUtc IS NULL) OR (IsDeleted = 1 AND DeletedAtUtc IS NOT NULL)");
                        });

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("NekoSubscription.Entities.Subscriptions.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("SubscriptionTags", b =>
                {
                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TagId")
                        .HasColumnType("TEXT");

                    b.HasKey("SubscriptionId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("SubscriptionTags", (string)null);
                });

            modelBuilder.Entity("NekoSubscription.Entities.Subscriptions.CloudServiceSubscription", b =>
                {
                    b.HasBaseType("NekoSubscription.Entities.Subscriptions.Subscription");

                    b.Property<int>("BillingMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProjectIdentifier")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantIdentifier")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasIndex("ProjectIdentifier");

                    b.HasIndex("TenantIdentifier");

                    b.ToTable("CloudServiceSubscriptions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Subscriptions_ArchiveState", "(IsArchived = 0 AND ArchivedAtUtc IS NULL) OR (IsArchived = 1 AND ArchivedAtUtc IS NOT NULL)");

                            t.HasCheckConstraint("CK_Subscriptions_DeleteState", "(IsDeleted = 0 AND DeletedAtUtc IS NULL) OR (IsDeleted = 1 AND DeletedAtUtc IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("NekoSubscription.Entities.Subscriptions.CustomSubscription", b =>
                {
                    b.HasBaseType("NekoSubscription.Entities.Subscriptions.Subscription");

                    b.ToTable("CustomSubscriptions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Subscriptions_ArchiveState", "(IsArchived = 0 AND ArchivedAtUtc IS NULL) OR (IsArchived = 1 AND ArchivedAtUtc IS NOT NULL)");

                            t.HasCheckConstraint("CK_Subscriptions_DeleteState", "(IsDeleted = 0 AND DeletedAtUtc IS NULL) OR (IsDeleted = 1 AND DeletedAtUtc IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("NekoSubscription.Entities.Subscriptions.DomainSubscription", b =>
                {
                    b.HasBaseType("NekoSubscription.Entities.Subscriptions.Subscription");

                    b.Property<string>("DomainName")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<DateOnly?>("ExpiresOn")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("RegisteredOn")
                        .HasColumnType("TEXT");

                    b.HasIndex("DomainName");

                    b.HasIndex("ExpiresOn");

                    b.ToTable("DomainSubscriptions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Subscriptions_ArchiveState", "(IsArchived = 0 AND ArchivedAtUtc IS NULL) OR (IsArchived = 1 AND ArchivedAtUtc IS NOT NULL)");

                            t.HasCheckConstraint("CK_Subscriptions_DeleteState", "(IsDeleted = 0 AND DeletedAtUtc IS NULL) OR (IsDeleted = 1 AND DeletedAtUtc IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("NekoSubscription.Entities.Subscriptions.OrdinarySubscription", b =>
                {
                    b.HasBaseType("NekoSubscription.Entities.Subscriptions.Subscription");

                    b.ToTable("OrdinarySubscriptions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Subscriptions_ArchiveState", "(IsArchived = 0 AND ArchivedAtUtc IS NULL) OR (IsArchived = 1 AND ArchivedAtUtc IS NOT NULL)");

                            t.HasCheckConstraint("CK_Subscriptions_DeleteState", "(IsDeleted = 0 AND DeletedAtUtc IS NULL) OR (IsDeleted = 1 AND DeletedAtUtc IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("NekoSubscription.Entities.Subscriptions.PhoneNumberSubscription", b =>
                {
                    b.HasBaseType("NekoSubscription.Entities.Subscriptions.Subscription");

                    b.Property<string>("CarrierName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrepaid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("PhoneNumberType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RegionName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasIndex("PhoneNumber");

                    b.ToTable("PhoneNumberSubscriptions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Subscriptions_ArchiveState", "(IsArchived = 0 AND ArchivedAtUtc IS NULL) OR (IsArchived = 1 AND ArchivedAtUtc IS NOT NULL)");

                            t.HasCheckConstraint("CK_Subscriptions_DeleteState", "(IsDeleted = 0 AND DeletedAtUtc IS NULL) OR (IsDeleted = 1 AND DeletedAtUtc IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("NekoSubscription.Entities.Subscriptions.CustomField", b =>
                {
                    b.HasOne("NekoSubscription.Entities.Subscriptions.CustomSubscription", "CustomSubscription")
                        .WithMany("Fields")
                        .HasForeignKey("CustomSubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomSubscription");
                });

            modelBuilder.Entity("NekoSubscription.Entities.Subscriptions.Subscription", b =>
                {
                    b.HasOne("NekoSubscription.Entities.Subscriptions.Subscription", "IncludedWithSubscription")
                        .WithMany("IncludedSubscriptions")
                        .HasForeignKey("IncludedWithSubscriptionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NekoSubscription.Entities.Subscriptions.PaymentProfile", "PaymentProfile")
                        .WithMany("Subscriptions")
                        .HasForeignKey("PaymentProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("NekoSubscription.Entities.Subscriptions.BillingSchedule", "BillingSchedule", b1 =>
                        {
                            b1.Property<Guid>("SubscriptionId")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("AutomaticallyRenews")
                                .HasColumnType("INTEGER")
                                .HasColumnName("AutomaticallyRenews");

                            b1.Property<int>("Cadence")
                                .HasColumnType("INTEGER")
                                .HasColumnName("BillingCadence");

                            b1.Property<DateOnly?>("EndsOn")
                                .HasColumnType("TEXT")
                                .HasColumnName("EndsOn");

                            b1.Property<int?>("IntervalCount")
                                .HasColumnType("INTEGER")
                                .HasColumnName("BillingIntervalCount");

                            b1.Property<int?>("IntervalUnit")
                                .HasColumnType("INTEGER")
                                .HasColumnName("BillingIntervalUnit");

                            b1.Property<DateOnly?>("NextBillingOn")
                                .HasColumnType("TEXT")
                                .HasColumnName("NextBillingOn");

                            b1.Property<DateOnly?>("StartsOn")
                                .HasColumnType("TEXT")
                                .HasColumnName("StartsOn");

                            b1.HasKey("SubscriptionId");

                            b1.HasIndex("NextBillingOn");

                            b1.ToTable("Subscriptions");

                            b1.WithOwner()
                                .HasForeignKey("SubscriptionId");
                        });

                    b.OwnsOne("NekoSubscription.Entities.Subscriptions.Money", "BillingAmount", b1 =>
                        {
                            b1.Property<Guid>("SubscriptionId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(28, 18)
                                .HasColumnType("TEXT")
                                .HasColumnName("BillingAmount");

                            b1.Property<string>("CurrencyCode")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("TEXT")
                                .HasColumnName("CurrencyCode");

                            b1.Property<int>("CurrencyKind")
                                .HasColumnType("INTEGER")
                                .HasColumnName("CurrencyKind");

                            b1.HasKey("SubscriptionId");

                            b1.ToTable("Subscriptions");

                            b1.WithOwner()
                                .HasForeignKey("SubscriptionId");
                        });

                    b.OwnsOne("NekoSubscription.Entities.Subscriptions.PaymentDeferralPolicy", "PaymentDeferralPolicy", b1 =>
                        {
                            b1.Property<Guid>("SubscriptionId")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("BudgetToleranceDays")
                                .HasColumnType("INTEGER")
                                .HasColumnName("BudgetToleranceDays");

                            b1.Property<int?>("ProviderGracePeriodDays")
                                .HasColumnType("INTEGER")
                                .HasColumnName("ProviderGracePeriodDays");

                            b1.HasKey("SubscriptionId");

                            b1.ToTable("Subscriptions");

                            b1.WithOwner()
                                .HasForeignKey("SubscriptionId");
                        });

                    b.Navigation("BillingAmount")
                        .IsRequired();

                    b.Navigation("BillingSchedule")
                        .IsRequired();

                    b.Navigation("IncludedWithSubscription");

                    b.Navigation("PaymentDeferralPolicy");

                    b.Navigation("PaymentProfile");
                });

            modelBuilder.Entity("SubscriptionTags", b =>
                {
                    b.HasOne("NekoSubscription.Entities.Subscriptions.Subscription", null)
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NekoSubscription.Entities.Subscriptions.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NekoSubscription.Entities.Subscriptions.CloudServiceSubscription", b =>
                {
                    b.HasOne("NekoSubscription.Entities.Subscriptions.Subscription", null)
                        .WithOne()
                        .HasForeignKey("NekoSubscription.Entities.Subscriptions.CloudServiceSubscription", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NekoSubscription.Entities.Subscriptions.CustomSubscription", b =>
                {
                    b.HasOne("NekoSubscription.Entities.Subscriptions.Subscription", null)
                        .WithOne()
                        .HasForeignKey("NekoSubscription.Entities.Subscriptions.CustomSubscription", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NekoSubscription.Entities.Subscriptions.DomainSubscription", b =>
                {
                    b.HasOne("NekoSubscription.Entities.Subscriptions.Subscription", null)
                        .WithOne()
                        .HasForeignKey("NekoSubscription.Entities.Subscriptions.DomainSubscription", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NekoSubscription.Entities.Subscriptions.OrdinarySubscription", b =>
                {
                    b.HasOne("NekoSubscription.Entities.Subscriptions.Subscription", null)
                        .WithOne()
                        .HasForeignKey("NekoSubscription.Entities.Subscriptions.OrdinarySubscription", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NekoSubscription.Entities.Subscriptions.PhoneNumberSubscription", b =>
                {
                    b.HasOne("NekoSubscription.Entities.Subscriptions.Subscription", null)
                        .WithOne()
                        .HasForeignKey("NekoSubscription.Entities.Subscriptions.PhoneNumberSubscription", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NekoSubscription.Entities.Subscriptions.PaymentProfile", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("NekoSubscription.Entities.Subscriptions.Subscription", b =>
                {
                    b.Navigation("IncludedSubscriptions");
                });

            modelBuilder.Entity("NekoSubscription.Entities.Subscriptions.CustomSubscription", b =>
                {
                    b.Navigation("Fields");
                });
#pragma warning restore 612, 618
        }
    }
}
