// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NekoSubscription.Core.Configuration;

#nullable disable

namespace NekoSubscription.Core.Configuration.Migrations
{
    [DbContext(typeof(ConfigurationDbContext))]
    [Migration("20260715030004_AddVisualStyleSettings")]
    partial class AddVisualStyleSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("NekoSubscription.Core.Configuration.ApplicationSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<double>("AcrylicOpacity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.84999999999999998);

                    b.Property<string>("CultureName")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("MinimumLogLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Theme")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("VisualStyle")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ApplicationSettings", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
