// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using NekoSubscription.Core.Configuration;
using NekoSubscription.Core.Configuration.CompiledModels;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(ConfigurationDbContext), typeof(ConfigurationDbContextModel))]
