// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace NekoSubscription.Core.Configuration.CompiledModels
{
    public partial class ConfigurationDbContextModel
    {
        private ConfigurationDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("655cabbb-454f-4374-8910-686bed554671"), entityTypeCount: 1)
        {
        }

        partial void Initialize()
        {
            var applicationSettings = ApplicationSettingsEntityType.Create(this);

            ApplicationSettingsEntityType.CreateAnnotations(applicationSettings);

            AddAnnotation("ProductVersion", "10.0.10");
        }
    }
}
